######################## default configuration ####################
baseURL = "https://staging.promitor.io/"
title = "Promitor"
theme = "bigspring"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "UA-117259584-1" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true
