############################# English ############################
[en]
languageName = "En"
title = "Promitor"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "Bringing Azure Monitor metrics where you need them."
# copyright
copyright = "© Promitor by Tom Kerkhove"