# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Documentation"
url = "https://promitor.io/"
weight = 2

[[main]]
name = "Pricing"
url = "pricing"
weight = 3

[[main]]
name = "Contact"
url = "contact"
weight = 4

[[main]]
name = "FAQ"
url = "faq"
weight = 5

[[main]]
name = "GitHub"
url = "https://github.com/tomkerkhove/promitor"
weight = 6

# footer menu left
[[footer_left]]
name = "Changelog"
url = "https://changelog.promitor.io/"

[[footer_left]]
name = "Pricing"
url = "pricing"

[[footer_left]]
name = "GitHub"
url = "https://github.com/tomkerkhove/promitor"


# footer menu middle
[[footer_middle]]
name = "Metrics"
url = "pricing"
[[footer_middle]]
name = "Deployment"
url = "pricing"
[[footer_middle]]
name = "Configuration"
url = "pricing"
[[footer_middle]]
name = "Security"
url = "pricing"

[[footer_middle]]
name = "Operations"
url = "#"

[[footer_middle]]
name = "Walkthroughs"
url = "#"

# footer menu right
[[footer_right]]
name = "Support Policy"
url = "https://github.com/tomkerkhove/promitor/blob/master/SUPPORT.md"
weight = 1

[[footer_right]]
name = "Report An Issue"
url = "https://github.com/tomkerkhove/promitor/issues/new/choose"
weight = 2

[[footer_right]]
name = "Get Support"
url = "pricing"
weight = 3

[[footer_right]]
name = "FAQ"
url = "faq"
weight = 4