# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Concepts"
url = "concepts"
weight = 2

# [[main]]
# name = "Docs"
# url = "https://docs.promitor.io/"
# weight = 3

# [[main]]
# name = "Pricing"
# url = "pricing"
# weight = 4

[[main]]
name = "FAQ"
url = "faq"
weight = 6

[[main]]
name = "Changelog"
url = "https://changelog.promitor.io/"
weight = 7

[[main]]
name = "GitHub"
url = "https://github.com/tomkerkhove/promitor"
weight = 8

# footer menu left
[[footer_left]]
name = "Changelog"
url = "https://changelog.promitor.io/"

# [[footer_left]]
# name = "Pricing"
# url = "pricing"

[[footer_left]]
name = "GitHub"
url = "https://github.com/tomkerkhove/promitor"

[[footer_left]]
name = "Legal"
url = "legal"


# footer menu middle
[[footer_middle]]
name = "Supported Azure Services"
url = "https://docs.promitor.io/configuration/v2.x/metrics/"
weight = 1

[[footer_middle]]
name = "Metric Sinks"
url = "https://docs.promitor.io/configuration/v2.x/runtime/scraper#metric-sinks"
weight = 2

[[footer_middle]]
name = "Deployment"
url = "https://docs.promitor.io/deployment"
weight = 3

[[footer_middle]]
name = "Operations"
url = "https://docs.promitor.io/operations"
weight = 4

[[footer_middle]]
name = "Security"
url = "https://docs.promitor.io/configuration/v2.x/azure-authentication"
weight = 5

# footer menu right
[[footer_right]]
name = "Support Policy"
url = "https://github.com/tomkerkhove/promitor/blob/master/SUPPORT.md"
weight = 1

[[footer_right]]
name = "Report An Issue"
url = "https://github.com/tomkerkhove/promitor/issues/new/choose"
weight = 2

# [[footer_right]]
# name = "Get Support"
# url = "pricing"
# weight = 3

[[footer_right]]
name = "FAQ"
url = "faq"
weight = 4