#################### default parameters ################################
logo = "images/logo.svg"
logo_width = "200px"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Tom Kerkhove"
image = "images/logo.svg" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "Docs"
link = "http://docs.promitor.io/"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"
  
############################# social site ########################
[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/promitorio"

[[social]]
title = "github"
icon = "fab fa-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/tomkerkhove/promitor"